Разделение страниц на компоненты
htmlacademy-react/816175-six-cities-15 pull request #2
Opened 2024-02-15 13:23 UTC by Bachinina

Привет! в чате группы задала вопросы, которые возникли в ходе выполнения))

2024-02-15 13:27 UTC, Bachinina commented
build посыпался, почему - не поняла
на lint прогоняла

2024-02-17 09:48 UTC, baileys-li requested changes

2024-02-17 09:48 UTC, baileys-li commented on src/const.ts
> +};
Чекни [критерий](https://up.htmlacademy.ru/react/15/criteries#b9) про енамки
```suggestion
export const enum Settings {
  ResultCount = 312
}
```

2024-02-17 09:48 UTC, baileys-li commented on src/components/card/card.tsx
> +  img: string;
Лучше затипизировать отдельно оффер, чтобы потом тайп чекать моковвые данные

2024-02-17 09:48 UTC, baileys-li commented on src/components/card/card.tsx
> +          <button className={`place-card__bookmark-button button ${props.isFavorite ? 'place-card__bookmark-button--active' : ''}`} type="button">
Булевые CSS классы обычно через [classnames ](https://www.npmjs.com/package/classnames )пишутся. А ещё лучше
```suggestion
    <button className={classNames('place-card__bookmark-button', 'button', {
            'place-card__bookmark-button--active': props.isFavorite
          })} type="button"
          >
```

А ещё лучше [clsx](https://www.npmjs.com/package/clsx)

2024-02-17 09:48 UTC, baileys-li commented on src/const.ts
> +export const Data = [{
Плохой нейминг
```suggestion
export const MOCK_OFFERS = [{
```

2024-02-21 14:53 UTC, merged